### ISSUE TITLE
Less space between rows in Listing component

### ISSUE THREAD

**Issue by JohanDurand-FashionData** [FashionData/maestro#157]
![image.png](https://images.zenhubusercontent.com/609ab8070a40bdd6136fe496/7235425a-711e-4b7e-ae85-5d3a48e642fd)

on this example it would be possible to have twice the number of rows we have now.

**Comment by Eronne** [comment]
What are we going to do with this issue @JohanDurand-FashionData

**Comment by JohanDurand-FashionData** [comment]
That's to make it possible to put more rows visible in the Sales reforecast
page on the Size breakdown part.

[image: Logo%20FD%20Long]

Johan Durand

Product Manager - Demand Forecast / Product Autopilot

***@***.***  ***@***.***>

+33 6 67 92 09 57

www.fashiondata.io



Le ven. 21 janv. 2022 à 15:44, Erwann Letue ***@***.***> a
écrit :
