### ISSUE TITLE
Add new DayJs to replace momentJs

### ISSUE THREAD

**Issue by bmartins-42** [FashionData/maestro#190]
## Scope
Maestro and depending applications

## Problem Description
MomentJs is deprecated and no longer maintained. To switch smoothly we agreed with @Eronne to add in first time a new date library and to migrate momentJS dependencies in other application when refactoring momentjs related code lines.

We choose DayJs due to is API close to MomentJS and is strong support/usage from the community 

## Your proposition

- [ ] install dayJs to maestro
- [ ] create new vue prototype
- [ ] replace momentJS usage in maestro

**Comment by Eronne** [comment]
This has been merged.
