### ISSUE TITLE
Add Account Object

### ISSUE THREAD

**Issue by romone22** [FashionData/maestro#38]
**Is your feature request related to a problem? Please describe.**
In order to organize group of users and specific parameters for this group, we need a account object.

**Describe the solution you'd like**
An account is an object associated to a user. It could be a organisation, a department aka any kind of users group.
Here is the account attributs
- A unique ID. It must be a string of maximum 6 digits - Mandatory
- A Name : String- Mandatory
- A status : Active / Disabled / Achived - Mandatory
- A Short description : String multilines - Not Mandatory
- A Website : URL - not mandatory
- A email for contact : email - not mandatory
- A Avatar : Square Image - Not Mandatory

**Additional context**
- The user must be a super admin to create an account
- The user must be admin of the account to update ou delete it

**Comment by Eronne** [comment]
@Liinkiing #48 Provides this isn't it?

**Comment by Liinkiing** [comment]
> @Liinkiing #48 Provides this isn't it?

Yes 👍
