### ISSUE TITLE
Attached User to Account

### ISSUE THREAD

**Issue by romone22** [FashionData/maestro#39]
**Is your feature request related to a problem? Please describe.**
Each User must have, at least, an account attached to his profile. 

**Describe the solution you'd like**
For each user's account, the role (From Suspended to Super Admin) must be set. 
The Role+Account attributes must be saved in the Firebase User Claims to secure the access. 
A user can have many attached accounts (be careful off the size of the access array in the firebase user claims which is very limited).
Only Super admin can manage users for any account
Only Admin can manager users for a the admin account

Maestro UIs: 
- an UI must provide a listing of users attached to accounts. 
- An CREATE USER button allow to create a user and attach roles ans accounts

**Comment by Eronne** [comment]
@Liinkiing #47 Provides this isn't it?

**Comment by Liinkiing** [comment]
> @Liinkiing #47 Provides this isn't it?

Yep 👍
