### ISSUE TITLE
Add accounts listing

### ISSUE THREAD

**Issue by Eronne** [FashionData/maestro#4]
**Is your feature request related to a problem? Please describe.**
Add accounts listing to manager each of them.

**Describe the solution you'd like**
A listing page which following actions can be done:
- Create
- Edit
- Delete

**Comment by Eronne** [comment]
Closing this issue as this will not being handled by maestro for the moment.

**Comment by Eronne** [comment]
@Liinkiing #48 Provides this isn't it?

**Comment by Liinkiing** [comment]
> @Liinkiing #48 Provides this isn't it?

👍
